# Generated by Django 5.1.1 on 2026-02-17 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(limit_choices_to={'tipo_usuario': 'ESS'}, on_delete=django.db.models.deletion.CASCADE, related_name='estacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
