# Generated by Django 6.0.2 on 2026-03-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('SUSPENDIDA', 'Suspendida')], db_index=True, default='ACTIVA', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estación de Servicio',
                'verbose_name_plural': 'Estaciones de Servicio',
                'ordering': ['departamento', 'municipio', 'nombre'],
            },
        ),
    ]
