# Generated by Django 6.0.2 on 2026-03-14 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionservicio',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por'),
        ),
        migrations.AddIndex(
            model_name='estacionservicio',
            index=models.Index(fields=['estado'], name='estaciones__estado_c98af2_idx'),
        ),
        migrations.AddIndex(
            model_name='estacionservicio',
            index=models.Index(fields=['departamento', 'municipio'], name='estaciones__departa_eab5bd_idx'),
        ),
    ]
