# Generated by Django 6.0.2 on 2026-03-14 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_expiracion_solicitudes_horas', models.PositiveIntegerField(default=72, help_text='Horas que tiene el consumidor para retirar el combustible después de que su solicitud es aprobada. Por defecto: 72h (3 días).', verbose_name='Expiración de solicitudes aprobadas (horas)')),
                ('litros_maximo_por_solicitud', models.PositiveIntegerField(default=120, help_text='Cantidad máxima de litros que un consumidor puede solicitar en una sola solicitud. Por defecto: 120 litros.', verbose_name='Límite máximo de litros por solicitud')),
                ('max_intentos_fallidos', models.PositiveIntegerField(default=5, help_text='Número de intentos fallidos consecutivos antes de bloquear la cuenta temporalmente. Por defecto: 5 intentos.', verbose_name='Máximo de intentos fallidos de login')),
                ('tiempo_bloqueo_minutos', models.PositiveIntegerField(default=15, help_text='Minutos que permanece bloqueada una cuenta tras superar el máximo de intentos fallidos. Por defecto: 15 minutos.', verbose_name='Tiempo de bloqueo por intentos fallidos (minutos)')),
                ('tiempo_expiracion_pin_minutos', models.PositiveIntegerField(default=15, help_text='Minutos de validez del PIN de 6 dígitos enviado por email para verificación de cuenta. Por defecto: 15 minutos.', verbose_name='Expiración de PIN de verificación (minutos)')),
                ('tiempo_expiracion_token_recuperacion_horas', models.PositiveIntegerField(default=1, help_text='Horas de validez del token enviado por email para recuperar la contraseña. Por defecto: 1 hora.', verbose_name='Expiración de token de recuperación de contraseña (horas)')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_actualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Última actualización por')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
    ]
