# Generated by Django 6.0.2 on 2026-04-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='dias_minimos_entre_solicitudes',
            field=models.PositiveIntegerField(default=7, help_text='Días que debe esperar un consumidor tras un despacho antes de crear una nueva solicitud. 0 = sin límite.', verbose_name='Días mínimos entre solicitudes'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='horas_aviso_expiracion_solicitud',
            field=models.PositiveIntegerField(default=24, help_text='Horas antes del vencimiento en que se notifica al consumidor que su solicitud está por expirar.', verbose_name='Horas de aviso antes de expiración'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='limite_litros_mensual',
            field=models.PositiveIntegerField(default=120, help_text='Total de litros despachados que puede acumular un consumidor en un mes. Por defecto: 120L.', verbose_name='Límite de litros por mes por consumidor'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='limite_litros_semanal',
            field=models.PositiveIntegerField(default=30, help_text='Total de litros despachados por semana. 0 = sin límite semanal. Por defecto: 30L.', verbose_name='Límite de litros por semana por consumidor'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='limite_solicitudes_por_periodo',
            field=models.PositiveIntegerField(default=3, help_text='Número de solicitudes APROBADAS o DESPACHADAS en el período que activa la alerta de repetitividad.', verbose_name='Límite de solicitudes por período'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='max_estaciones_distintas_por_mes',
            field=models.PositiveIntegerField(default=2, help_text='Si un consumidor retira en más estaciones distintas que este valor en un mes, se activa alerta de rotación.', verbose_name='Máximo de estaciones distintas por mes'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='periodo_control_solicitudes_dias',
            field=models.PositiveIntegerField(default=30, help_text='Ventana de días para contar solicitudes por consumidor.', verbose_name='Período de control de repetitividad (días)'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='litros_maximo_por_solicitud',
            field=models.PositiveIntegerField(default=120, help_text='Máximo de litros por solicitud. Por defecto: 120L.', verbose_name='Límite máximo de litros por solicitud'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='max_intentos_fallidos',
            field=models.PositiveIntegerField(default=5, help_text='Intentos antes de bloquear la cuenta. Por defecto: 5.', verbose_name='Máximo de intentos fallidos de login'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='tiempo_bloqueo_minutos',
            field=models.PositiveIntegerField(default=15, help_text='Minutos de bloqueo tras superar intentos fallidos. Por defecto: 15.', verbose_name='Tiempo de bloqueo por intentos fallidos (minutos)'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='tiempo_expiracion_pin_minutos',
            field=models.PositiveIntegerField(default=15, help_text='Validez del PIN de 6 dígitos enviado por email. Por defecto: 15 min.', verbose_name='Expiración de PIN de verificación (minutos)'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='tiempo_expiracion_solicitudes_horas',
            field=models.PositiveIntegerField(default=72, help_text='Horas para retirar el combustible tras la aprobación. Por defecto: 72h.', verbose_name='Expiración de solicitudes aprobadas (horas)'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='tiempo_expiracion_token_recuperacion_horas',
            field=models.PositiveIntegerField(default=1, help_text='Validez del token de recuperación de contraseña. Por defecto: 1 hora.', verbose_name='Expiración de token de recuperación (horas)'),
        ),
    ]
