# Generated by Django 6.0.2 on 2026-04-03 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Departamento')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Provincia')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provincias', to='catalogos.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['departamento__nombre', 'nombre'],
                'unique_together': {('departamento', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Municipio')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='catalogos.provincia', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['provincia__nombre', 'nombre'],
                'unique_together': {('provincia', 'nombre')},
            },
        ),
    ]
