# Generated by Django 6.0.2 on 2026-03-14 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumidorPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('celular', models.CharField(blank=True, default='', max_length=20, verbose_name='Celular')),
                ('estado_identidad', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('VERIFICADO', 'Verificado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado de identidad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consumidor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil Consumidor',
                'verbose_name_plural': 'Perfiles Consumidor',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoIdentidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CI', 'Cédula de Identidad'), ('LICENCIA', 'Licencia de Conducir'), ('EXTRANJERO', 'Carnet de Extranjero')], max_length=20, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=30, unique=True, verbose_name='Número de documento')),
                ('complemento_documento', models.CharField(blank=True, default='', max_length=10, verbose_name='Complemento')),
                ('anverso', models.ImageField(upload_to='documentos/identidad/anverso/', verbose_name='Anverso')),
                ('reverso', models.ImageField(upload_to='documentos/identidad/reverso/', verbose_name='Reverso')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='consumidores.consumidorperfil', verbose_name='Perfil consumidor')),
            ],
            options={
                'verbose_name': 'Documento de Identidad',
                'verbose_name_plural': 'Documentos de Identidad',
                'ordering': ['-fecha_subida'],
                'constraints': [models.UniqueConstraint(fields=('perfil', 'tipo_documento'), name='unique_tipo_documento_por_perfil')],
            },
        ),
    ]
