# Generated by Django 5.1.1 on 2026-02-17 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumidores', '0001_initial'),
        ('estaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumidorperfil',
            name='estacion_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumidores', to='estaciones.estacionservicio', verbose_name='Estación de Servicio'),
        ),
    ]
