# Generated by Django 6.0.2 on 2026-04-03 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('consumidores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumidorperfil',
            name='actividad',
            field=models.CharField(blank=True, choices=[('AGRICULTURA', 'Agricultura / Ganadería'), ('TRANSPORTE', 'Transporte'), ('INDUSTRIA', 'Industria / Manufactura'), ('PESCA', 'Pesca'), ('CONSTRUCCION', 'Construcción'), ('DOMESTICO', 'Uso doméstico'), ('COMERCIO', 'Comercio'), ('MINERIA', 'Minería'), ('OTRO', 'Otro')], default='', max_length=20, verbose_name='Actividad económica'),
        ),
        migrations.AddField(
            model_name='consumidorperfil',
            name='alerta_repetitividad',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('EN_REVISION', 'En revisión por repetitividad'), ('BLOQUEADO', 'Bloqueado')], db_index=True, default='NORMAL', max_length=20, verbose_name='Alerta de repetitividad'),
        ),
        migrations.AddField(
            model_name='consumidorperfil',
            name='celular_verificado',
            field=models.BooleanField(default=False, verbose_name='Celular verificado'),
        ),
        migrations.AddField(
            model_name='consumidorperfil',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumidores', to='catalogos.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='consumidorperfil',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='consumidorperfil',
            name='fecha_alerta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de alerta'),
        ),
        migrations.AddField(
            model_name='consumidorperfil',
            name='motivo_bloqueo',
            field=models.TextField(blank=True, default='', verbose_name='Motivo de bloqueo'),
        ),
        migrations.AddField(
            model_name='consumidorperfil',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumidores', to='catalogos.municipio', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='consumidorperfil',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumidores', to='catalogos.provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='documentoidentidad',
            name='foto_sosteniendo',
            field=models.ImageField(blank=True, help_text='Fotografía del solicitante sosteniendo su documento de identidad de frente. Requerida para nuevos registros.', null=True, upload_to='documentos/identidad/sosteniendo/', verbose_name='Foto sosteniendo el documento'),
        ),
        migrations.AlterField(
            model_name='documentoidentidad',
            name='anverso',
            field=models.ImageField(upload_to='documentos/identidad/anverso/', verbose_name='Anverso del documento'),
        ),
        migrations.AlterField(
            model_name='documentoidentidad',
            name='reverso',
            field=models.ImageField(upload_to='documentos/identidad/reverso/', verbose_name='Reverso del documento'),
        ),
        migrations.AlterField(
            model_name='documentoidentidad',
            name='tipo_documento',
            field=models.CharField(choices=[('CI', 'Cédula de Identidad (CI)'), ('CIE', 'Cédula de Identidad de Extranjero (CIE)')], max_length=20, verbose_name='Tipo de documento'),
        ),
    ]
