# Generated by Django 6.0.2 on 2026-03-14 04:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumidores', '0001_initial'),
        ('estaciones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publico', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('OBSERVADA', 'Observada'), ('RECHAZADA', 'Rechazada'), ('APROBADA', 'Aprobada'), ('DESPACHADA', 'Despachada'), ('EXPIRADA', 'Expirada')], db_index=True, default='PENDIENTE', max_length=20)),
                ('tipo_combustible', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diésel'), ('GNV', 'GNV')], max_length=20)),
                ('litros_solicitados', models.PositiveIntegerField()),
                ('tipo_combustible_aprobado', models.CharField(blank=True, choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diésel'), ('GNV', 'GNV')], max_length=20, null=True)),
                ('litros_aprobados', models.PositiveIntegerField(blank=True, null=True)),
                ('observacion_anh', models.TextField(blank=True)),
                ('litros_despachados', models.PositiveIntegerField(blank=True, help_text='Litros realmente entregados por la estación. Puede ser menor a litros_aprobados si no había stock suficiente.', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_asignacion_estacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('fecha_despacho', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='consumidores.consumidorperfil')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
                ('despachado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_despachadas', to=settings.AUTH_USER_MODEL)),
                ('estacion_asignada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_estacion_asignadas', to=settings.AUTH_USER_MODEL)),
                ('estacion_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='estaciones.estacionservicio')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado'], name='solicitudes_estado_d46b95_idx'), models.Index(fields=['estado', 'fecha_creacion'], name='solicitudes_estado_4a4fe5_idx'), models.Index(fields=['consumidor', 'estado'], name='solicitudes_consumi_aa6683_idx'), models.Index(fields=['estacion_servicio', 'estado'], name='solicitudes_estacio_9e1af2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'OBSERVADA', 'APROBADA'])), fields=('consumidor',), name='unique_solicitud_activa_por_consumidor')],
            },
        ),
    ]
