# Generated by Django 5.1.1 on 2026-02-17 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumidores', '0002_consumidorperfil_estacion_servicio'),
        ('estaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='consumidores.consumidorperfil')),
                ('estacion_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='estaciones.estacionservicio')),
            ],
        ),
    ]
