# Generated by Django 6.0.2 on 2026-04-03 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='actividad',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Actividad económica'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='declaracion_jurada_confirmada',
            field=models.BooleanField(default=False, verbose_name='Declaración jurada confirmada'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='catalogos.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='documento_justificativo',
            field=models.FileField(blank=True, help_text='Documento opcional que justifica el uso del combustible.', null=True, upload_to='solicitudes/documentos_justificativos/', verbose_name='Documento justificativo'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_declaracion_jurada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación declaración jurada'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='catalogos.municipio', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='catalogos.provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='uso_combustible',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Uso / destino del combustible'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('OBSERVADA', 'Observada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada'), ('APROBADA', 'Aprobada'), ('DESPACHADA', 'Despachada'), ('EXPIRADA', 'Expirada')], db_index=True, default='PENDIENTE', max_length=20),
        ),
    ]
