# Generated by Django 6.0.2 on 2026-04-06 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_solicitud_actividad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaEstadoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(max_length=20, verbose_name='Estado nuevo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('nota', models.TextField(blank=True, default='', verbose_name='Nota')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditoria', to='solicitudes.solicitud', verbose_name='Solicitud')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_solicitudes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Auditoría de Solicitud',
                'verbose_name_plural': 'Auditoría de Solicitudes',
                'ordering': ['-fecha'],
            },
        ),
    ]
