# Generated by Django 6.0.2 on 2026-04-30 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('consumidores', '0002_consumidorperfil_actividad_and_more'),
        ('estaciones', '0002_initial'),
        ('solicitudes', '0003_auditoriaestadosolicitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_limite_respuesta',
            field=models.DateTimeField(blank=True, help_text='El consumidor tiene hasta esta fecha para responder la observación. Se calcula automáticamente: fecha_observacion + 24 horas.', null=True, verbose_name='Fecha límite de respuesta'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_observacion',
            field=models.DateTimeField(blank=True, help_text='Momento en que la ANH marcó la solicitud como OBSERVADA.', null=True, verbose_name='Fecha de observación'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='respuesta_consumidor',
            field=models.TextField(blank=True, default='', help_text='Justificación o aclaración del consumidor ante una observación de la ANH.', verbose_name='Respuesta del consumidor'),
        ),
        migrations.AlterField(
            model_name='auditoriaestadosolicitud',
            name='estado_anterior',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='auditoriaestadosolicitud',
            name='estado_nuevo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='auditoriaestadosolicitud',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='auditoriaestadosolicitud',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditoriaestadosolicitud',
            name='nota',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='auditoriaestadosolicitud',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_solicitudes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='documento_justificativo',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes/documentos_justificativos/', verbose_name='Documento justificativo'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='litros_despachados',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='observacion_anh',
            field=models.TextField(blank=True, help_text='Motivo de observación o rechazo por parte de la ANH.', verbose_name='Observación ANH'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['estado', 'fecha_limite_respuesta'], name='solicitudes_estado_3454f7_idx'),
        ),
    ]
