# Generated by Django 6.0.2 on 2026-05-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_solicitud_fecha_limite_respuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='documento_respuesta',
            field=models.FileField(blank=True, help_text='Documento adjunto por el consumidor al responder una observación.', null=True, upload_to='solicitudes/documentos_respuesta/', verbose_name='Documento de respuesta'),
        ),
    ]
