# Generated by Django 6.0.2 on 2026-03-14 04:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('estaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, default='', max_length=100, verbose_name='Apellido materno')),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Administrador'), ('ANH', 'Personal ANH'), ('ESS', 'Personal Estación'), ('CONS', 'Consumidor')], max_length=10, verbose_name='Tipo de usuario')),
                ('estado_cuenta', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido')], default='PENDIENTE', max_length=20, verbose_name='Estado de cuenta')),
                ('email_verificado', models.BooleanField(default=False, verbose_name='Email verificado')),
                ('requiere_cambio_password', models.BooleanField(default=False, verbose_name='Requiere cambio de contraseña')),
                ('intentos_fallidos', models.IntegerField(default=0, verbose_name='Intentos fallidos de inicio de sesión')),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado hasta')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['apellido_paterno', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='PerfilFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CI', 'Cédula de Identidad'), ('PASAPORTE', 'Pasaporte'), ('EXTRANJERO', 'Carnet de Extranjero')], max_length=20, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de documento')),
                ('complemento_documento', models.CharField(blank=True, default='', max_length=10, verbose_name='Complemento')),
                ('numero_funcionario', models.CharField(max_length=30, unique=True, verbose_name='Número de funcionario')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('unidad_departamento', models.CharField(max_length=100, verbose_name='Unidad / Departamento')),
                ('celular', models.CharField(blank=True, default='', max_length=20, verbose_name='Celular')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estacion_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='estaciones.estacionservicio', verbose_name='Estación de servicio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_funcionario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil Funcionario',
                'verbose_name_plural': 'Perfiles Funcionario',
            },
        ),
        migrations.CreateModel(
            name='TokenVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('codigo_pin', models.CharField(blank=True, default='', max_length=6, verbose_name='Código PIN')),
                ('tipo', models.CharField(choices=[('EMAIL', 'Verificación Email'), ('RECUP', 'Recuperación Password')], max_length=10, verbose_name='Tipo')),
                ('usado', models.BooleanField(default=False, verbose_name='Usado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_verificacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token de verificación',
                'verbose_name_plural': 'Tokens de verificación',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
